apiVersion: v2
name: apten-chat-web
description: Frontend for apten-chat messenger
type: application
version: 0.1.0
appVersion: "0.0.1"
keywords:
  - chat
  - frontend
  - web
maintainers:
  - name: Alex
